<?php
$this->fpdf->AddPage('P');
$this->fpdf->Image('logo_kkt.png',20,10,30);
$this->fpdf->Ln(2);
$this->fpdf->SetFont('Arial', 'B', 11);
$this->fpdf->Cell(0, 7, 'DAILY REPORT WATER TREATMENT PLANT', 0, 1, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(0, 7, 'PT. KALTIM KARIANGAU TERMINAL', 0, 1, 'C');
$this->fpdf->Ln(10);
$this->fpdf->SetFont('Arial', '', 10);
$this->fpdf->SetTextColor(0, 0, 0);
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'Hari / Tanggal', 0, 'L');
$this->fpdf->Cell(10, 7, ':', 0,0, 'R');
$this->fpdf->Cell(70, 7, '  '.$hasil['tanggal_transaksi'], 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'Nama Perusahaan / Kapal', 0, 'L');
$this->fpdf->Cell(10, 7, ':', 0,0, 'R');
$this->fpdf->Cell(70, 7, '  '.$hasil['nama_agent'].' / '.$hasil['nama_vessel'], 0, 'L');
$this->fpdf->Ln(12);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, 'Jam', 1,0, 'C');
$this->fpdf->Cell(140, 7, 'Keterangan', 1,1, 'C');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, $hasil['jam_pelayanan'].' WITA', 'LTR',0, 'C');
$this->fpdf->Cell(140, 7, 'Informasi dari pihak Perencanaan bahwa kapal '.$hasil['nama_vessel'], 'LTR',1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, '', 'LRB',0, 'C');
$this->fpdf->Cell(140, 7, 'akan melakukan bunker air bersih sebanyak '.$hasil['total_permohonan'].' ton.', 'LRB',1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, $hasil['jam_pelayanan'].' WITA', 1,0, 'C');
$this->fpdf->Cell(140, 7, 'Konfirmasi ulang kepada pihak kapal dan dilakukan persiapan pengisian.', 1,1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, $hasil['jam_mulai'].' WITA', 'LTR',0, 'C');
$this->fpdf->Cell(140, 7, 'Awal pengisian, angka yang tertera pada flow meter di dermaga adalah ', 'LTR',1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, '', 'LRB',0, 'C');
$this->fpdf->Cell(140, 7, $hasil['flowmeter_awal'].','.$hasil['flowmeter_awal_2'].','.$hasil['flowmeter_awal_3'].','.$hasil['flowmeter_awal_4'].'.', 'LRB',1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, $hasil['jam_akhir'].' WITA', 'LTR',0, 'C');
$this->fpdf->Cell(140, 7, 'Selesai pengisian air bersih dengan angka yang tertera pada flow meter di dermaga ', 'LTR',1, 'L');
$this->fpdf->Ln(0);
$this->fpdf->Cell(10, 7, '', 0, 'C');
$this->fpdf->Cell(25, 7, '', 'LRB',0, 'C');
$this->fpdf->Cell(140, 7, $hasil['flowmeter_akhir'].','.$hasil['flowmeter_akhir_2'].','.$hasil['flowmeter_akhir_3'].','.$hasil['flowmeter_akhir_4'].'. '.'Total keseluruhan pengisian air bersih adalah '.$hasil['total_pengisian'].' ton.', 'LRB',1, 'L');
$this->fpdf->Ln(12);
$this->fpdf->Ln();
$this->fpdf->Cell(80, 7, '', 0,0, 'C');
$this->fpdf->Cell(140, 7, 'Balikpapan, '.$hasil['tanggal_dokumen'], 0,0, 'C');
$this->fpdf->Ln();
$this->fpdf->Cell(80, 7, 'PERUSAHAAN / KAPAL', 0,0, 'C');
$this->fpdf->Cell(140, 7, 'OPERATOR WTP', 0,0, 'C');
$this->fpdf->Ln(25);
$this->fpdf->Cell(80, 7, '', 0,0, 'C');
$this->fpdf->Cell(140, 7, '', 0,0, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(80, 7, '(................................................)', 0,0, 'C');
$this->fpdf->Cell(140, 7, '(................................................)', 0,0, 'C');
$this->fpdf->Cell(80, 7, '', 0,0, 'C');
$this->fpdf->Cell(140, 7, '', 0,0, 'C');
$this->fpdf->Ln(20);
$this->fpdf->Cell(185, 7, 'PEMBUAT LAPORAN', 0,0, 'C');
$this->fpdf->Ln(5);
$this->fpdf->Ln(25);
$this->fpdf->Cell(185, 7, '', 0,0, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(185, 7, '(................................................)', 0,0, 'C');
$this->fpdf->Ln(20);
$this->fpdf->Cell(185, 7, 'MENGETAHUI,', 0,0, 'C');
$this->fpdf->Ln(5);
$this->fpdf->Cell(185, 7, 'ASMAN OPERASI PELAYANAN NON PETIKEMAS', 0,0, 'C');
$this->fpdf->Ln(25);
$this->fpdf->Cell(185, 7, 'BERLY KARDIN SENAPATI', 0,0, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(185, 7, '(................................................)', 0,0, 'C');
$this->fpdf->Output("form_permintaan.pdf","I");

?>