<?php
$this->fpdf->AddPage('P');
$this->fpdf->Image('logo_kkt.png',85,10,30);
$this->fpdf->Ln(24);
$this->fpdf->SetFont('Arial', 'B', 11);
$this->fpdf->Ln();
$this->fpdf->Cell(0, 7, 'PERMOHONAN KEGIATAN PELAYANAN AIR BERSIH', 0, 1, 'C');
$this->fpdf->Ln();
$this->fpdf->SetFont('Arial', 'B', 10);
$this->fpdf->SetTextColor(0, 0, 0);
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'Yang Bertanda Tangan Di Bawah Ini : ', 0, 'L');
$this->fpdf->Ln(12);
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, '1. NAMA PERUSAHAAN', 0, 'L');
$this->fpdf->Cell(10, 7, ':', 0,0, 'R');
$this->fpdf->Cell(70, 7, '  '.$hasil['nama_agent'], 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, '2. ALAMAT', 0, 'L');
$this->fpdf->Cell(10, 7, ':', 0,0, 'R');
$this->fpdf->Cell(70, 7, '  '.$hasil['alamat'], 0, 'L');
$this->fpdf->Ln(12);
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'Berdasarkan Peraturan yang berlaku, mohon untuk dapat diberikan pelayanan air bersih untuk kapal ', 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'sebagai berikut : ', 0, 'L');
$this->fpdf->Ln(12);
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'NAMA KAPAL / VOY', 0, 'L');
$this->fpdf->Cell(25, 7, ':', 0,0, 'R');
$this->fpdf->Cell(90, 7, '  '.$hasil['nama_vessel'].' / '.$hasil['voy_no'], 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'GT / LOA', 0, 'L');
$this->fpdf->Cell(25, 7, ':', 0,0, 'R');
$this->fpdf->Cell(90, 7, '  ', 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'TANGGAL PENGISIAN', 0, 'L');
$this->fpdf->Cell(25, 7, ':', 0,0, 'R');
$this->fpdf->Cell(90, 7, '  '.$hasil['tanggal'], 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'JAM PENGISIAN', 0, 'L');
$this->fpdf->Cell(25, 7, ':', 0,0, 'R');
$this->fpdf->Cell(90, 7, '  '.$hasil['jam']." WITA", 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Cell(10, 7, '', 0, 'L');
$this->fpdf->Cell(40, 7, 'TOTAL PERMOHONAN PENGISIAN', 0, 'L');
$this->fpdf->Cell(25, 7, ':', 0,0, 'R');
$this->fpdf->Cell(90, 7, '  '.$hasil['total_permohonan']." Ton", 0, 'L');
$this->fpdf->Ln();
$this->fpdf->Ln();
$this->fpdf->Ln(20);
$this->fpdf->Cell(80, 7, 'Menyetujui', 0,0, 'C');
$this->fpdf->Cell(140, 7, 'Balikpapan, '.$hasil['tgl_transaksi'], 0,0, 'C');
$this->fpdf->Ln();
$this->fpdf->Cell(80, 7, 'AN. Manager Operasi Dan Komersial', 0,0, 'C');
$this->fpdf->Cell(140, 7, 'Pemakai Jasa', 0,0, 'C');
$this->fpdf->Ln(25);
$this->fpdf->Cell(80, 7, '', 0,0, 'C');
$this->fpdf->SetFont('Arial', 'B', 7);
$this->fpdf->Cell(140, 7, $hasil['nama_agent'], 0,0, 'C');
$this->fpdf->SetFont('Arial', 'B', 10);
$this->fpdf->Ln(1);
$this->fpdf->Cell(80, 7, '(................................................)', 0,0, 'C');
$this->fpdf->Cell(140, 7, '(......................................................)', 0,0, 'C');
$this->fpdf->Output("form_permintaan.pdf","I");

?>