<?php
$this->fpdf->AddPage('L',array(215.9,139.7));
$this->fpdf->SetFont('Arial', '', 10);
$this->fpdf->Ln();
$this->fpdf->Cell(0, 1, 'PT KALTIM KARIANGAU TERMINAL', 0, 1, 'L');
$this->fpdf->SetFont('Arial', '', 10);
$this->fpdf->Ln();
$this->fpdf->Cell(0, 9, 'TERMINAL PETIKEMAS KARIANGAU', 0, 1, 'L');
$this->fpdf->SetFont('Arial', '', 12);
$this->fpdf->Ln(3);
$this->fpdf->Cell(0, 7, 'KWITANSI PELAYANAN JASA AIR BERSIH', 0, 1, 'C');
$this->fpdf->Ln(1);
$this->fpdf->SetFont('Arial', '', 11);
$this->fpdf->SetTextColor(0, 0, 0);
$this->fpdf->Cell(40, 7, 'No Kwitansi', 0, 'L');
$this->fpdf->Cell(5, 7, ':', 0, 'L');
$this->fpdf->Cell(50, 7, $hasil['kwitansi'], 0, 'L');
$this->fpdf->Cell(40, 7, 'Nama Pemohon', 0, 'L');
$this->fpdf->Cell(5, 7, ':', 0, 'L');
$this->fpdf->Cell(10, 7, $hasil['nama_pemohon'], 0, 'L');
$this->fpdf->Ln(5);
$this->fpdf->Cell(40, 7, 'Nama Pelanggan', 0, 'L');
$this->fpdf->Cell(5, 7, ':', 0, 'L');
$this->fpdf->Cell(50, 7, $hasil['nama_pelanggan'], 0, 'L');
$this->fpdf->Cell(40, 7, 'Tanggal Permintaan', 0, 'L');
$this->fpdf->Cell(5, 7, ':', 0, 'L');
$this->fpdf->Cell(10, 7, $hasil['tgl_perm'], 0, 'L');
$this->fpdf->Ln(5);
$this->fpdf->Cell(40, 7, 'Alamat', 0, 'L');
$this->fpdf->Cell(5, 7, ':', 0, 'L');
$this->fpdf->Cell(90, 7, $hasil['alamat'], 0, 'L');
$this->fpdf->Ln(8);
$this->fpdf->Cell(7, 7, 'No', 1,0, 'C');
$this->fpdf->Cell(40, 7, 'Jenis Pelayanan', 1,0, 'C');
$this->fpdf->Cell(30, 7, ' Satuan', 1,0, 'C');
$this->fpdf->Cell(35, 7, ' Total Pengisian', 1,0, 'C');
$this->fpdf->Cell(25, 7, ' Tarif', 1,0, 'C');
$this->fpdf->Cell(50, 7, ' Total Pembayaran', 1,0, 'C');
$this->fpdf->Ln();
$this->fpdf->Cell(7, 7, '1', 1,0, 'C');
$this->fpdf->Cell(40, 7, 'Pengisian Air Bersih', 1,0, 'C');
$this->fpdf->Cell(30, 7, 'Ton', 1,0, 'C');
$this->fpdf->Cell(35, 7, $hasil['total_pengisian'], 1,0, 'C');
$this->fpdf->Cell(25, 7, 'Rp. '.$hasil['tarif'], 1,0, 'C');
$this->fpdf->Cell(50, 7, 'Rp. '.$hasil['total'], 1,0, 'C');
$this->fpdf->Ln(8);
$this->fpdf->SetFont('Arial', '', 11);
$this->fpdf->Cell(25, 7, 'Terbilang : ', 0,0, 'L');
$this->fpdf->SetFont('Arial', 'I', 11);
$this->fpdf->Cell(5, 7, $hasil['terbilang'], 0,0, 'L');
$this->fpdf->Ln(6);
$this->fpdf->Cell(10, 10, '', 0, 'R');
$this->fpdf->SetFont('Arial', '', 11);
$this->fpdf->Cell(300, 3, 'Balikpapan, ' . $hasil['tanggal'], 0, 0, 'C');
$this->fpdf->Ln(5);
$this->fpdf->Cell(55, 3, 'Konsumen', 0, 0, 'C');
$this->fpdf->Cell(210, 3, 'PT. Kaltim Kariangau Terminal', 0, 0, 'C');
$this->fpdf->Ln(5);
$this->fpdf->Cell(320, 3, 'Operator Pengisian Air Bersih', 0, 0, 'C');
$this->fpdf->Ln(7);
$this->fpdf->Cell(55, 3, $hasil['nama_pemohon'], 0, 0, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(55, 3, '(..........................................)', 0, 0, 'C');
$this->fpdf->Ln(12);
$this->fpdf->Cell(55, 3, 'Loket', 0, 0, 'C');
$this->fpdf->Cell(210, 3, 'Kasir', 0, 0, 'C');
$this->fpdf->Ln(14);
$this->fpdf->Cell(55, 3, $hasil['loket'], 0, 0, 'C');
$this->fpdf->Ln(1);
$this->fpdf->Cell(55, 3, '(..........................................)', 0, 0, 'C');
$this->fpdf->Cell(210, 3, '(..........................................)', 0, 0, 'C');
$this->fpdf->Output("kwitansi-".$hasil['nama_pemohon'].".pdf","I");

?>